fullName: John Doe
bio: Full-stack developer & open source enthusiast
avatar: https://i.pravatar.cc/128
links:
  - title: Portfolio
    url: https://portfolio.com
    icon: mdi:briefcase
    classes: 'btn-primary'
  - title: Blog
    url: https://blog.com
    icon: mdi:book
    classes: 'btn-secondary'
  - title: YouTube
    url: https://youtube.com
    icon: mdi:video
    classes: 'btn-danger'
socials:
  - title: Twitter
    url: https://twitter.com
    icon: mdi:twitter
  - title: GitHub
    url: https://github.com
    icon: mdi:github
  - title: LinkedIn
    url: https://linkedin.com
    icon: mdi:linkedin